import type {
  DemoComplex,
  DemoConsultationLog,
  DemoContract,
  DemoInquiry,
  DemoPriceTerms,
  DemoProperty,
  DemoState,
} from "./types";

export const DEMO_SEED_ID = "realconnect-portfolio-2026-09";

const EMPTY_PRICE: DemoPriceTerms = {
  sale: 0,
  jeonse: 0,
  monthlyDeposit: 0,
  monthlyRent: 0,
};

const complexes: DemoComplex[] = [
  {
    id: "complex-hanbit",
    name: "한빛샘플아파트",
    address: "서울특별시 샘플구 포트폴리오로 101",
    district: "샘플구",
    legalDong: "샘플동",
    builtYear: 2015,
    totalHouseholds: 842,
    parkingPerHousehold: 1.21,
  },
  {
    id: "complex-pureunddeul",
    name: "푸른뜰데모아파트",
    address: "서울특별시 샘플구 이력서길 24",
    district: "샘플구",
    legalDong: "가람동",
    builtYear: 2019,
    totalHouseholds: 618,
    parkingPerHousehold: 1.34,
  },
];

type PropertySeed = Omit<
  DemoProperty,
  "propertyType" | "rooms" | "bathrooms" | "registeredAt" | "updatedAt"
> & {
  rooms?: number;
  bathrooms?: number;
  registeredAt?: string;
  updatedAt?: string;
};

function property(seed: PropertySeed): DemoProperty {
  return {
    propertyType: "APARTMENT",
    rooms: seed.exclusiveArea >= 80 ? 3 : 2,
    bathrooms: seed.exclusiveArea >= 80 ? 2 : 1,
    registeredAt: "2026-08-20T09:00:00.000Z",
    updatedAt: "2026-09-10T09:00:00.000Z",
    ...seed,
  };
}

const properties: DemoProperty[] = [
  property({
    id: "property-001",
    complexId: "complex-hanbit",
    building: "101동",
    unit: "1203호",
    floor: 12,
    totalFloor: 24,
    supplyArea: 112.4,
    exclusiveArea: 84.96,
    direction: "SOUTH",
    transactionType: "SALE",
    status: "AVAILABLE",
    priority: "ATTENTION",
    price: { ...EMPTY_PRICE, sale: 128000 },
    owner: { name: "김하늘(데모)", phone: "010-0000-0001" },
    occupancyStatus: "OWNER_OCCUPIED",
    availableFrom: "2026-11-15",
    isFavorite: true,
    tags: ["로열동", "남향", "수리완료"],
    memo: "주말 오전 방문 선호. 포트폴리오용 가상 매물입니다.",
    updatedAt: "2026-09-13T06:20:00.000Z",
  }),
  property({
    id: "property-002",
    complexId: "complex-hanbit",
    building: "102동",
    unit: "805호",
    floor: 8,
    totalFloor: 22,
    supplyArea: 112.4,
    exclusiveArea: 84.96,
    direction: "SOUTHEAST",
    transactionType: "JEONSE",
    status: "CONSULTING",
    priority: "NORMAL",
    price: { ...EMPTY_PRICE, jeonse: 72000 },
    owner: { name: "이도윤(데모)", phone: "010-0000-0002" },
    occupancyStatus: "JEONSE",
    availableFrom: "2026-10-30",
    isFavorite: false,
    tags: ["역세권", "확장형"],
    memo: "기존 임차인과 방문 일정 조율 필요.",
    updatedAt: "2026-09-12T03:10:00.000Z",
  }),
  property({
    id: "property-003",
    complexId: "complex-hanbit",
    building: "103동",
    unit: "1502호",
    floor: 15,
    totalFloor: 21,
    supplyArea: 82.1,
    exclusiveArea: 59.87,
    direction: "SOUTHWEST",
    transactionType: "MONTHLY",
    status: "AVAILABLE",
    priority: "ATTENTION",
    price: { ...EMPTY_PRICE, monthlyDeposit: 10000, monthlyRent: 250 },
    owner: { name: "박서연(데모)", phone: "010-0000-0003" },
    occupancyStatus: "VACANT",
    availableFrom: "2026-09-20",
    isFavorite: true,
    tags: ["즉시입주", "고층", "공실"],
    memo: "도어락 비밀번호는 데모 데이터에 저장하지 않음.",
    updatedAt: "2026-09-14T01:30:00.000Z",
  }),
  property({
    id: "property-004",
    complexId: "complex-hanbit",
    building: "104동",
    unit: "402호",
    floor: 4,
    totalFloor: 20,
    supplyArea: 82.1,
    exclusiveArea: 59.87,
    direction: "EAST",
    transactionType: "SALE",
    status: "AVAILABLE",
    priority: "NORMAL",
    price: { ...EMPTY_PRICE, sale: 89000 },
    owner: { name: "최민준(데모)", phone: "010-0000-0004" },
    occupancyStatus: "OWNER_OCCUPIED",
    availableFrom: "2026-12-01",
    isFavorite: false,
    tags: ["초등학교인접", "급매"],
    memo: "가격 조정 가능 범위는 상담 후 확인.",
  }),
  property({
    id: "property-005",
    complexId: "complex-hanbit",
    building: "105동",
    unit: "1101호",
    floor: 11,
    totalFloor: 23,
    supplyArea: 82.1,
    exclusiveArea: 59.87,
    direction: "SOUTH",
    transactionType: "JEONSE",
    status: "AVAILABLE",
    priority: "NORMAL",
    price: { ...EMPTY_PRICE, jeonse: 48000 },
    owner: { name: "정지우(데모)", phone: "010-0000-0005" },
    occupancyStatus: "VACANT",
    availableFrom: "2026-09-25",
    isFavorite: true,
    tags: ["남향", "공실", "채광좋음"],
    memo: "평일 저녁에도 방문 가능.",
  }),
  property({
    id: "property-006",
    complexId: "complex-hanbit",
    building: "106동",
    unit: "1904호",
    floor: 19,
    totalFloor: 25,
    supplyArea: 148.9,
    exclusiveArea: 114.82,
    rooms: 4,
    bathrooms: 2,
    direction: "SOUTHEAST",
    transactionType: "SALE",
    status: "CONTRACTING",
    priority: "ATTENTION",
    price: { ...EMPTY_PRICE, sale: 175000 },
    owner: { name: "강윤서(데모)", phone: "010-0000-0006" },
    occupancyStatus: "OWNER_OCCUPIED",
    availableFrom: "2027-01-10",
    isFavorite: true,
    tags: ["대형평형", "로열층", "계약협의"],
    memo: "계약서 초안 검토 중.",
    updatedAt: "2026-09-14T02:15:00.000Z",
  }),
  property({
    id: "property-007",
    complexId: "complex-hanbit",
    building: "107동",
    unit: "307호",
    floor: 3,
    totalFloor: 18,
    supplyArea: 68.5,
    exclusiveArea: 49.75,
    direction: "WEST",
    transactionType: "MONTHLY",
    status: "AVAILABLE",
    priority: "CAUTION",
    price: { ...EMPTY_PRICE, monthlyDeposit: 5000, monthlyRent: 190 },
    owner: { name: "조현우(데모)", phone: "010-0000-0007" },
    occupancyStatus: "MONTHLY",
    availableFrom: "2026-10-15",
    isFavorite: false,
    tags: ["소형평형", "반려동물협의"],
    memo: "관리비 체납 여부를 계약 전 재확인.",
  }),
  property({
    id: "property-008",
    complexId: "complex-hanbit",
    building: "108동",
    unit: "2102호",
    floor: 21,
    totalFloor: 24,
    supplyArea: 112.4,
    exclusiveArea: 84.96,
    direction: "SOUTH",
    transactionType: "SALE",
    status: "COMPLETED",
    priority: "NORMAL",
    price: { ...EMPTY_PRICE, sale: 131000 },
    owner: { name: "윤가은(데모)", phone: "010-0000-0008" },
    occupancyStatus: "VACANT",
    availableFrom: "2026-09-01",
    isFavorite: false,
    tags: ["계약완료"],
    memo: "포트폴리오 계약 완료 사례.",
    updatedAt: "2026-09-08T08:00:00.000Z",
  }),
  property({
    id: "property-009",
    complexId: "complex-hanbit",
    building: "109동",
    unit: "602호",
    floor: 6,
    totalFloor: 19,
    supplyArea: 112.4,
    exclusiveArea: 84.96,
    direction: "NORTHEAST",
    transactionType: "JEONSE",
    status: "HOLD",
    priority: "CAUTION",
    price: { ...EMPTY_PRICE, jeonse: 68000 },
    owner: { name: "임시온(데모)", phone: "010-0000-0009" },
    occupancyStatus: "OWNER_OCCUPIED",
    availableFrom: "2026-12-20",
    isFavorite: false,
    tags: ["보류", "일정확인"],
    memo: "소유자 요청으로 9월 말까지 광고 보류.",
  }),
  property({
    id: "property-010",
    complexId: "complex-pureunddeul",
    building: "201동",
    unit: "1401호",
    floor: 14,
    totalFloor: 25,
    supplyArea: 110.8,
    exclusiveArea: 84.72,
    direction: "SOUTH",
    transactionType: "SALE",
    status: "AVAILABLE",
    priority: "ATTENTION",
    price: { ...EMPTY_PRICE, sale: 116000 },
    owner: { name: "한지민(데모)", phone: "010-0000-0010" },
    occupancyStatus: "OWNER_OCCUPIED",
    availableFrom: "2026-11-30",
    isFavorite: true,
    tags: ["공원뷰", "남향", "시스템에어컨"],
    memo: "사진 촬영 동의 완료.",
    updatedAt: "2026-09-13T12:40:00.000Z",
  }),
  property({
    id: "property-011",
    complexId: "complex-pureunddeul",
    building: "202동",
    unit: "903호",
    floor: 9,
    totalFloor: 23,
    supplyArea: 110.8,
    exclusiveArea: 84.72,
    direction: "SOUTHEAST",
    transactionType: "JEONSE",
    status: "AVAILABLE",
    priority: "NORMAL",
    price: { ...EMPTY_PRICE, jeonse: 65000 },
    owner: { name: "오예준(데모)", phone: "010-0000-0011" },
    occupancyStatus: "JEONSE",
    availableFrom: "2026-10-31",
    isFavorite: true,
    tags: ["신축급", "커뮤니티"],
    memo: "보증보험 가능 여부 확인 완료.",
  }),
  property({
    id: "property-012",
    complexId: "complex-pureunddeul",
    building: "203동",
    unit: "1704호",
    floor: 17,
    totalFloor: 24,
    supplyArea: 110.8,
    exclusiveArea: 84.72,
    direction: "SOUTHWEST",
    transactionType: "MONTHLY",
    status: "CONSULTING",
    priority: "ATTENTION",
    price: { ...EMPTY_PRICE, monthlyDeposit: 8000, monthlyRent: 220 },
    owner: { name: "신채원(데모)", phone: "010-0000-0012" },
    occupancyStatus: "VACANT",
    availableFrom: "2026-09-18",
    isFavorite: false,
    tags: ["즉시입주", "공원뷰"],
    memo: "법인 임차 가능.",
  }),
  property({
    id: "property-013",
    complexId: "complex-pureunddeul",
    building: "204동",
    unit: "505호",
    floor: 5,
    totalFloor: 21,
    supplyArea: 81.7,
    exclusiveArea: 59.92,
    direction: "EAST",
    transactionType: "SALE",
    status: "AVAILABLE",
    priority: "NORMAL",
    price: { ...EMPTY_PRICE, sale: 82000 },
    owner: { name: "문서준(데모)", phone: "010-0000-0013" },
    occupancyStatus: "OWNER_OCCUPIED",
    availableFrom: "2026-12-05",
    isFavorite: false,
    tags: ["첫입주", "학원가"],
    memo: "가격은 최근 실거래가 확인 후 협의.",
  }),
  property({
    id: "property-014",
    complexId: "complex-pureunddeul",
    building: "205동",
    unit: "1302호",
    floor: 13,
    totalFloor: 22,
    supplyArea: 81.7,
    exclusiveArea: 59.92,
    direction: "SOUTH",
    transactionType: "JEONSE",
    status: "AVAILABLE",
    priority: "NORMAL",
    price: { ...EMPTY_PRICE, jeonse: 45500 },
    owner: { name: "배수아(데모)", phone: "010-0000-0014" },
    occupancyStatus: "VACANT",
    availableFrom: "2026-09-22",
    isFavorite: false,
    tags: ["공실", "남향"],
    memo: "도배 후 인도 예정.",
  }),
  property({
    id: "property-015",
    complexId: "complex-pureunddeul",
    building: "206동",
    unit: "706호",
    floor: 7,
    totalFloor: 20,
    supplyArea: 67.9,
    exclusiveArea: 49.61,
    direction: "SOUTH",
    transactionType: "MONTHLY",
    status: "AVAILABLE",
    priority: "NORMAL",
    price: { ...EMPTY_PRICE, monthlyDeposit: 3000, monthlyRent: 165 },
    owner: { name: "유태오(데모)", phone: "010-0000-0015" },
    occupancyStatus: "VACANT",
    availableFrom: "2026-09-19",
    isFavorite: true,
    tags: ["1인가구", "즉시입주", "남향"],
    memo: "전입신고 가능.",
    updatedAt: "2026-09-14T00:50:00.000Z",
  }),
  property({
    id: "property-016",
    complexId: "complex-pureunddeul",
    building: "207동",
    unit: "1801호",
    floor: 18,
    totalFloor: 25,
    supplyArea: 132.7,
    exclusiveArea: 101.34,
    rooms: 4,
    bathrooms: 2,
    direction: "SOUTHEAST",
    transactionType: "SALE",
    status: "CONSULTING",
    priority: "ATTENTION",
    price: { ...EMPTY_PRICE, sale: 148000 },
    owner: { name: "노은호(데모)", phone: "010-0000-0016" },
    occupancyStatus: "OWNER_OCCUPIED",
    availableFrom: "2027-01-31",
    isFavorite: true,
    tags: ["대형평형", "공원뷰"],
    memo: "매수 희망 고객 1팀 상담 중.",
  }),
  property({
    id: "property-017",
    complexId: "complex-pureunddeul",
    building: "208동",
    unit: "1004호",
    floor: 10,
    totalFloor: 22,
    supplyArea: 110.8,
    exclusiveArea: 84.72,
    direction: "SOUTHWEST",
    transactionType: "JEONSE",
    status: "COMPLETED",
    priority: "NORMAL",
    price: { ...EMPTY_PRICE, jeonse: 63000 },
    owner: { name: "서나연(데모)", phone: "010-0000-0017" },
    occupancyStatus: "VACANT",
    availableFrom: "2026-09-10",
    isFavorite: false,
    tags: ["계약완료"],
    memo: "전자계약 완료 데모 사례.",
    updatedAt: "2026-09-09T07:25:00.000Z",
  }),
  property({
    id: "property-018",
    complexId: "complex-pureunddeul",
    building: "209동",
    unit: "203호",
    floor: 2,
    totalFloor: 19,
    supplyArea: 81.7,
    exclusiveArea: 59.92,
    direction: "NORTHWEST",
    transactionType: "SALE",
    status: "HOLD",
    priority: "CAUTION",
    price: { ...EMPTY_PRICE, sale: 79000 },
    owner: { name: "홍다인(데모)", phone: "010-0000-0018" },
    occupancyStatus: "MONTHLY",
    availableFrom: "2027-02-28",
    isFavorite: false,
    tags: ["보류", "임대차승계"],
    memo: "임대차 승계 조건 정리 전까지 보류.",
  }),
];

type InquirySeed = Omit<
  DemoInquiry,
  "propertyType" | "createdAt" | "updatedAt"
> & {
  createdAt?: string;
  updatedAt?: string;
};

function inquiry(seed: InquirySeed): DemoInquiry {
  return {
    propertyType: "APARTMENT",
    createdAt: "2026-09-01T09:00:00.000Z",
    updatedAt: "2026-09-10T09:00:00.000Z",
    ...seed,
  };
}

const inquiries: DemoInquiry[] = [
  inquiry({
    id: "inquiry-001",
    title: "한빛 84㎡ 남향 매매 문의",
    customer: { name: "고은별(데모)", phone: "010-0000-1001", relation: "본인" },
    transactionType: "SALE",
    status: "VISIT_SCHEDULED",
    priority: "ATTENTION",
    desiredComplexIds: ["complex-hanbit"],
    desiredDistricts: ["샘플구"],
    desiredDongs: ["샘플동"],
    area: { min: 80, max: 90 },
    budget: {
      sale: { min: 120000, max: 135000 },
      jeonse: null,
      monthlyDeposit: null,
      monthlyRent: null,
    },
    moveInBy: "2026-12-15",
    publicDescription: "남향, 중층 이상을 우선 검토합니다.",
    privateNote: "토요일 오전 방문 예약. 가상 고객입니다.",
    updatedAt: "2026-09-14T02:00:00.000Z",
  }),
  inquiry({
    id: "inquiry-002",
    title: "샘플동 59㎡ 전세 문의",
    customer: { name: "김로운(데모)", phone: "010-0000-1002", relation: "본인" },
    transactionType: "JEONSE",
    status: "CONTACTED",
    priority: "NORMAL",
    desiredComplexIds: [],
    desiredDistricts: ["샘플구"],
    desiredDongs: ["샘플동"],
    area: { min: 55, max: 65 },
    budget: {
      sale: null,
      jeonse: { min: 45000, max: 52000 },
      monthlyDeposit: null,
      monthlyRent: null,
    },
    moveInBy: "2026-10-20",
    publicDescription: "공실 또는 빠른 입주 가능 매물을 찾습니다.",
    privateNote: "보증보험 가입 가능 여부 중요.",
  }),
  inquiry({
    id: "inquiry-003",
    title: "가람동 소형 월세 문의",
    customer: { name: "이새봄(데모)", phone: "010-0000-1003", relation: "본인" },
    transactionType: "MONTHLY",
    status: "NEW",
    priority: "NORMAL",
    desiredComplexIds: ["complex-pureunddeul"],
    desiredDistricts: ["샘플구"],
    desiredDongs: ["가람동"],
    area: { min: 45, max: 60 },
    budget: {
      sale: null,
      jeonse: null,
      monthlyDeposit: { min: 0, max: 6000 },
      monthlyRent: { min: 130, max: 190 },
    },
    moveInBy: "2026-10-01",
    publicDescription: "1인 거주, 전입신고 가능한 집을 찾습니다.",
    privateNote: "반려동물 없음.",
    updatedAt: "2026-09-13T11:00:00.000Z",
  }),
  inquiry({
    id: "inquiry-004",
    title: "샘플구 100㎡ 이상 매매",
    customer: { name: "박도하(데모)", phone: "010-0000-1004", relation: "배우자" },
    transactionType: "SALE",
    status: "NEGOTIATING",
    priority: "ATTENTION",
    desiredComplexIds: [],
    desiredDistricts: ["샘플구"],
    desiredDongs: [],
    area: { min: 100, max: 120 },
    budget: {
      sale: { min: 140000, max: 180000 },
      jeonse: null,
      monthlyDeposit: null,
      monthlyRent: null,
    },
    moveInBy: "2027-02-28",
    publicDescription: "방 4개, 주차 여유 있는 대형 평형 선호.",
    privateNote: "기존 주택 처분 일정과 잔금일 연동 필요.",
    updatedAt: "2026-09-14T03:20:00.000Z",
  }),
  inquiry({
    id: "inquiry-005",
    title: "푸른뜰 84㎡ 전세 문의",
    customer: { name: "최라온(데모)", phone: "010-0000-1005", relation: "본인" },
    transactionType: "JEONSE",
    status: "VISIT_SCHEDULED",
    priority: "ATTENTION",
    desiredComplexIds: ["complex-pureunddeul"],
    desiredDistricts: ["샘플구"],
    desiredDongs: ["가람동"],
    area: { min: 80, max: 90 },
    budget: {
      sale: null,
      jeonse: { min: 60000, max: 70000 },
      monthlyDeposit: null,
      monthlyRent: null,
    },
    moveInBy: "2026-11-10",
    publicDescription: "커뮤니티 시설과 공원 접근성을 봅니다.",
    privateNote: "수요일 오후 방문 예정.",
  }),
  inquiry({
    id: "inquiry-006",
    title: "한빛 59㎡ 월세 문의",
    customer: { name: "정하람(데모)", phone: "010-0000-1006", relation: "자녀" },
    transactionType: "MONTHLY",
    status: "CONTACTED",
    priority: "NORMAL",
    desiredComplexIds: ["complex-hanbit"],
    desiredDistricts: ["샘플구"],
    desiredDongs: ["샘플동"],
    area: { min: 55, max: 65 },
    budget: {
      sale: null,
      jeonse: null,
      monthlyDeposit: { min: 5000, max: 12000 },
      monthlyRent: { min: 180, max: 260 },
    },
    moveInBy: "2026-10-15",
    publicDescription: "고층과 채광을 우선합니다.",
    privateNote: "직장 재직증명 가능.",
  }),
  inquiry({
    id: "inquiry-007",
    title: "샘플동 59㎡ 실거주 매매",
    customer: { name: "송이안(데모)", phone: "010-0000-1007", relation: "본인" },
    transactionType: "SALE",
    status: "ON_HOLD",
    priority: "CAUTION",
    desiredComplexIds: [],
    desiredDistricts: ["샘플구"],
    desiredDongs: ["샘플동"],
    area: { min: 55, max: 65 },
    budget: {
      sale: { min: 75000, max: 95000 },
      jeonse: null,
      monthlyDeposit: null,
      monthlyRent: null,
    },
    moveInBy: "2027-01-31",
    publicDescription: "초등학교 도보권을 선호합니다.",
    privateNote: "대출 사전심사 후 상담 재개.",
  }),
  inquiry({
    id: "inquiry-008",
    title: "샘플구 84㎡ 전세 비교",
    customer: { name: "장유나(데모)", phone: "010-0000-1008", relation: "본인" },
    transactionType: "JEONSE",
    status: "COMPLETED",
    priority: "NORMAL",
    desiredComplexIds: [],
    desiredDistricts: ["샘플구"],
    desiredDongs: [],
    area: { min: 80, max: 90 },
    budget: {
      sale: null,
      jeonse: { min: 60000, max: 78000 },
      monthlyDeposit: null,
      monthlyRent: null,
    },
    moveInBy: "2026-10-31",
    publicDescription: "두 단지를 함께 비교했습니다.",
    privateNote: "푸른뜰 계약 완료. 전 과정은 데모입니다.",
    updatedAt: "2026-09-09T07:30:00.000Z",
  }),
];

const consultations: DemoConsultationLog[] = [
  {
    id: "consultation-001",
    targetType: "INQUIRY",
    targetId: "inquiry-001",
    customerType: "BUYER",
    channel: "PHONE",
    content: "예산과 입주 희망일을 확인하고 후보 매물 2건을 안내함.",
    writerName: "김데모",
    createdAt: "2026-09-11T01:20:00.000Z",
  },
  {
    id: "consultation-002",
    targetType: "INQUIRY",
    targetId: "inquiry-001",
    customerType: "BUYER",
    channel: "MESSAGE",
    content: "property-001 방문 일정을 토요일 오전으로 확정함.",
    writerName: "김데모",
    createdAt: "2026-09-14T02:00:00.000Z",
  },
  {
    id: "consultation-003",
    targetType: "PROPERTY",
    targetId: "property-001",
    customerType: "OWNER",
    channel: "PHONE",
    content: "방문 전날 소유자에게 다시 연락하기로 함.",
    writerName: "김데모",
    createdAt: "2026-09-13T06:20:00.000Z",
  },
  {
    id: "consultation-004",
    targetType: "INQUIRY",
    targetId: "inquiry-002",
    customerType: "TENANT",
    channel: "PHONE",
    content: "보증보험과 빠른 입주가 우선 조건임을 확인함.",
    writerName: "김데모",
    createdAt: "2026-09-10T05:00:00.000Z",
  },
  {
    id: "consultation-005",
    targetType: "PROPERTY",
    targetId: "property-005",
    customerType: "OWNER",
    channel: "MESSAGE",
    content: "도배 완료 예정일과 열쇠 수령 방법을 확인함.",
    writerName: "김데모",
    createdAt: "2026-09-12T08:40:00.000Z",
  },
  {
    id: "consultation-006",
    targetType: "INQUIRY",
    targetId: "inquiry-003",
    customerType: "TENANT",
    channel: "EMAIL",
    content: "푸른뜰 소형 월세 매물 요약을 전송함.",
    writerName: "김데모",
    createdAt: "2026-09-13T11:00:00.000Z",
  },
  {
    id: "consultation-007",
    targetType: "INQUIRY",
    targetId: "inquiry-004",
    customerType: "BUYER",
    channel: "VISIT",
    content: "대형 평형 2건을 비교하고 property-006 가격 협의를 요청함.",
    writerName: "김데모",
    createdAt: "2026-09-12T04:30:00.000Z",
  },
  {
    id: "consultation-008",
    targetType: "PROPERTY",
    targetId: "property-006",
    customerType: "OWNER",
    channel: "PHONE",
    content: "계약 조건 초안을 공유하고 잔금일을 협의함.",
    writerName: "김데모",
    createdAt: "2026-09-14T02:15:00.000Z",
  },
  {
    id: "consultation-009",
    targetType: "INQUIRY",
    targetId: "inquiry-005",
    customerType: "TENANT",
    channel: "MESSAGE",
    content: "수요일 오후 푸른뜰 202동 방문을 확정함.",
    writerName: "김데모",
    createdAt: "2026-09-12T09:10:00.000Z",
  },
  {
    id: "consultation-010",
    targetType: "PROPERTY",
    targetId: "property-012",
    customerType: "OWNER",
    channel: "PHONE",
    content: "법인 임차 시 필요 서류를 안내함.",
    writerName: "김데모",
    createdAt: "2026-09-11T07:45:00.000Z",
  },
  {
    id: "consultation-011",
    targetType: "INQUIRY",
    targetId: "inquiry-006",
    customerType: "TENANT",
    channel: "PHONE",
    content: "보증금과 월세 범위를 재확인함.",
    writerName: "김데모",
    createdAt: "2026-09-10T02:30:00.000Z",
  },
  {
    id: "consultation-012",
    targetType: "INQUIRY",
    targetId: "inquiry-008",
    customerType: "TENANT",
    channel: "VISIT",
    content: "푸른뜰 208동 계약 조건에 최종 동의함.",
    writerName: "김데모",
    createdAt: "2026-09-09T07:30:00.000Z",
  },
];

const contracts: DemoContract[] = [
  {
    id: "contract-001",
    propertyId: "property-006",
    inquiryId: "inquiry-004",
    transactionType: "SALE",
    status: "IN_PROGRESS",
    lessorOrSeller: { name: "강윤서(데모)", phone: "010-0000-0006" },
    lesseeOrBuyer: { name: "박도하(데모)", phone: "010-0000-1004" },
    price: { ...EMPTY_PRICE, sale: 172000 },
    contractDate: "2026-09-20",
    moveInDate: "2027-01-10",
    expiresAt: "",
    memo: "계약서 초안 검토 중인 가상 사례.",
    updatedAt: "2026-09-14T02:15:00.000Z",
  },
  {
    id: "contract-002",
    propertyId: "property-008",
    transactionType: "SALE",
    status: "SIGNED",
    lessorOrSeller: { name: "윤가은(데모)", phone: "010-0000-0008" },
    lesseeOrBuyer: { name: "계약고객A(데모)", phone: "010-0000-2001" },
    price: { ...EMPTY_PRICE, sale: 130000 },
    contractDate: "2026-09-08",
    moveInDate: "2026-10-30",
    expiresAt: "",
    memo: "서명 완료된 매매 계약 데모.",
    updatedAt: "2026-09-08T08:00:00.000Z",
  },
  {
    id: "contract-003",
    propertyId: "property-017",
    inquiryId: "inquiry-008",
    transactionType: "JEONSE",
    status: "SIGNED",
    lessorOrSeller: { name: "서나연(데모)", phone: "010-0000-0017" },
    lesseeOrBuyer: { name: "장유나(데모)", phone: "010-0000-1008" },
    price: { ...EMPTY_PRICE, jeonse: 63000 },
    contractDate: "2026-09-09",
    moveInDate: "2026-10-20",
    expiresAt: "2028-10-19",
    memo: "전자계약 서명 완료 가상 사례.",
    updatedAt: "2026-09-09T07:30:00.000Z",
  },
  {
    id: "contract-004",
    propertyId: "property-002",
    transactionType: "JEONSE",
    status: "DRAFT",
    lessorOrSeller: { name: "이도윤(데모)", phone: "010-0000-0002" },
    lesseeOrBuyer: { name: "계약고객B(데모)", phone: "010-0000-2002" },
    price: { ...EMPTY_PRICE, jeonse: 71000 },
    contractDate: "2026-09-25",
    moveInDate: "2026-10-30",
    expiresAt: "2028-10-29",
    memo: "당사자 확인 전 계약 초안.",
    updatedAt: "2026-09-12T03:10:00.000Z",
  },
];

/** Returns a fresh object graph so callers can safely mutate their demo state. */
export function createDemoSeed(): DemoState {
  return {
    seedId: DEMO_SEED_ID,
    revision: 0,
    office: {
      id: "office-demo-001",
      name: "샘플한빛공인중개사사무소",
      representativeName: "김데모",
      registrationNumber: "00000-2026-00001",
      phone: "02-0000-0000",
      email: "demo@portfolio.invalid",
      address: "서울특별시 샘플구 포트폴리오로 10, 1층",
      businessHours: "평일 09:00–18:00 · 토요일 예약제",
      introduction: "취업 포트폴리오 시연을 위한 가상 중개사무소입니다.",
    },
    complexes: structuredCopy(complexes),
    properties: structuredCopy(properties),
    inquiries: structuredCopy(inquiries),
    consultations: structuredCopy(consultations),
    contracts: structuredCopy(contracts),
  };
}

function structuredCopy<T>(value: T): T {
  if (typeof structuredClone === "function") {
    return structuredClone(value);
  }

  return JSON.parse(JSON.stringify(value)) as T;
}
